---
title: "One Factor ANOVA"
author: C. Perez
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Description

An ongoing project to explore and understand various R methods used to verify ANOVA assumptions. There will typically be three files for each project; one will contain the code (**.R**), another will be markdown (**.Rmd**), and the last (**.pdf**) can be viewed directly in github. The (.pdf) file description includes the associated project description.
&nbsp;  


## Description of Files

#### one_factor.rmd  
A markdown file with an output converted to ".pdf" for github viewer compatibility.  

#### one_factor.pdf
Viewable output of one_factor.rmd file. This project explores the assumptions of the ANOVA test in the one factor (one-way) setting, and various tools available in R to verify these assumptions prior to conducting the analysis. Some tools explored in this analysis are as follows: Shapiro-Wilk's Normality Test, Levene's Test for Equality of Variance, Tukey's Honest Significant Difference Test, distribution visualization (histograms, boxplots), and further exploratory data analysis.

#### one_factor.r
A script file containing the code used in the ".rmd" files.

#### README.rmd
This file creates a README.md file for the repository.

###### Note: data is not provided in the repository.


